# Local development configuration
# This file should be added to .gitignore and never committed

spring:
  datasource:
    username: postgres
    password: n3u3d4!

jwt:
  secret: "ThisIsAVeryLongSecretKeyThatIsAtLeast512BitsLongForHS512AlgorithmTokenGenerationAndValidationPurposeExactly64BytesLong1234567890"
