spring:
  application:
    name: portfolio-app

  datasource:
    url: jdbc:postgresql://localhost:5432/leaping_db
    driver-class-name: org.postgresql.Driver
    username: 
    password: 

  flyway:
    locations: classpath:db/migration 
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect



