spring:
  application:
    name: portfolio-app

  datasource:
    url: jdbc:postgresql://localhost:5432/leaping_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}


  flyway:
    locations: classpath:db/migration 
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24 hours in milliseconds

